version: '3.3'
services:
  rusty-trader:
    container_name: rusty-trader
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_KEY=${SECRET_KEY}
    entrypoint: bash -c "target/release/rusty-trader"
