# This compose file is for local testing only. For deployment, pull the latest image from github
version: '3.3'
services:
  rusty-trader:
    container_name: rusty-trader
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_KEY=${SECRET_KEY}
