# This compose is only for local testing, see README for an example of a production compose
version: '3.3'
services:
  rusty-trader:
    container_name: rusty-trader
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - ACCESS_KEY=${ALPACA_ACCESS_KEY}
      - SECRET_KEY=${ALPACA_SECRET_KEY}
