[package]
name = "common"
version = { workspace = true }
edition = "2021"

[dependencies]
mongodb = "2"
tokio = { workspace = true }
serde = { version = "1", features = ["derive"] }
log = { workspace = true }