name: Build Pipline

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    branches: master

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: init/
      - name: Get Version
        id: get_version
        run: |
          cd init
          echo "version=$(cargo pkgid)" >> "$GITHUB_OUTPUT"
          echo "# Init Summary" >> $GITHUB_STEP_SUMMARY
          echo "Found package version: $(cargo pkgid)"  >> $GITHUB_STEP_SUMMARY

  tests:
    needs:
      - init
    uses: ./.github/workflows/RunTests.yaml

  build:
    needs:
      - init
      - tests
    uses: ./.github/workflows/DockerBuild.yaml
    with:
      version: ${{ needs.init.outputs.version }}
