name: Deploy Image

on:
  workflow_call:
    inputs:
      version:
        description: Package version
        type: string
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "# Deploy Summary 📦" >> $GITHUB_STEP_SUMMARY
          echo "Target: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: deploy/

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: deploy/
          push: true
          tags: ${{ inputs.version }}
