name: Build Image

on:
  workflow_call:
    inputs:
      version:
        description: Package version
        type: string
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "# Deploy Summary 📦" >> $GITHUB_STEP_SUMMARY
          echo "Target: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" >> $GITHUB_STEP_SUMMARY

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to registry
        run: |
          docker tag ${{ env.IMAGE_NAME }}:${{ inputs.version }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.version }}
          docker push ${{ env.IMAGE_NAME }}:${{ inputs.version }}
          echo "Deployed to: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
