name: Run Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: tests/

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy    
          rustup component add rustfmt

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Lint
        run: |
          cd tests
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Test
        run: |
          cd tests
          cargo check
          echo "# Test Summary ⚙️" >> $GITHUB_STEP_SUMMARY
          cargo test --all >> $GITHUB_STEP_SUMMARY
